# Generated by Django 4.2.28 on 2026-02-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('current_ndvi', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('historical_avg_5y', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('deviation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cloud_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
